name: onservice24
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  steps_indicator: ^1.4.0

  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.10
  firebase_messaging_platform_interface: ^4.5.17

  image_picker: ^1.1.0
  image_cropper: ^5.0.1
  mime: ^1.0.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.3
  shared_preferences: ^2.2.3
  shared_preferences_foundation: ^2.5.4
  path: ^1.9.0
  http: ^0.13.6
  dio: ^5.4.1
  provider: ^6.1.2
  flutter_easyloading: ^3.0.5
  flutter_offline: ^2.1.0
  fluttertoast: ^8.2.4
  card_swiper: ^3.0.1

  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  favorite_button: ^0.0.4
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  dartz: ^0.10.1
  get_it: ^7.6.7
  retrofit: ^4.1.0
  logger: ^2.0.2+1
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  sizer: ^2.0.15
  auto_size_text: ^3.0.0
  injectable: ^2.4.1
  pull_to_refresh_flutter3: ^2.0.0

  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  animation_wrappers: ^3.0.0
  rxdart: ^0.27.7
  animated_splash_screen: ^1.3.0
  flutter_switch: ^0.3.2
  flutter_onboarding_slider: ^1.0.11
  flutter_typeahead: ^4.8.0

  device_preview: ^1.1.0
  google_maps_flutter: ^2.6.1
  location: ^5.0.3
  geolocator: ^11.0.0
  country_picker: ^2.0.24
  readmore: ^3.0.0
  google_map_marker_animation: ^1.0.0+2
  share_plus: ^7.2.1
  map_picker: ^0.1.0
  geocoding: ^3.0.0
  loading_indicator: ^3.1.0
  sms_otp_auto_verify:
    path: lib_plugins/sms_otp_auto_verify

  custom_map_markers: ^1.0.0
  flutter_timer_countdown: ^1.0.0
  local_auth: ^2.1.8
  pulsator: ^0.0.3
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^8.0.2
  intl: ^0.18.1
  flutter_local_notifications: ^17.1.2

  win32: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  retrofit_generator: ^8.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  analyzer: ^6.4.1
  flutter_lints: ^2.0.3

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  background_image: "assets/logo/logo.png"
  android12: true
  android_12:
    background_image: "assets/logo/logo.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/loading.gif
    - assets/images/logo.png
    - assets/images/terms_ar.pdf
    - assets/images/terms_en.pdf
    - assets/logo/
    - assets/logo/logo.png
    - assets/json/map_style.txt

  fonts:
    - family: Cairo-Black
      fonts:
        - asset: assets/font/Cairo/Cairo-Black.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/font/Cairo/Cairo-Bold.ttf
    - family: Cairo-ExtraBold
      fonts:
        - asset: assets/font/Cairo/Cairo-ExtraBold.ttf
    - family: Cairo-ExtraLight
      fonts:
        - asset: assets/font/Cairo/Cairo-ExtraLight.ttf
    - family: Cairo-Light
      fonts:
        - asset: assets/font/Cairo/Cairo-Light.ttf
    - family: Cairo-Medium
      fonts:
        - asset: assets/font/Cairo/Cairo-Medium.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/font/Cairo/Cairo-Regular.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: assets/font/Cairo/Cairo-SemiBold.ttf
